config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :products
  root 'page#home'
  get 'page/home'

  get 'page/menu'

  get 'page/contact'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	def add
		id = params[:id]

		if session[:cart] then
			cart = session[:cart]
		else
			session[:cart] = {}
			cart = session[:cart]
		end

		if cart[id] then
			cart[id] = cart[id] + 1
		else
			cart[id] = 1
		end
		redirect_to :action => :index
	end

	def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end

	def index
		if session[:cart] then
			@cart = session[:cart]
		else
			@cart = {}
		end
	end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def menu
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @burger = Burger.find(params[:id])
    @cart_action = @burger.cart_action current_user.try :id
  end
=begin
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<%= link_to 'Empty Your Cart', cart_clear_path%>
<br><br><br>

<% total = 0 %>

<ul>
<% @cart.each do | id, quantity | %>
	<% product = Product.find_by_id(id) %>

	<li>
	<% link_to product.title, product %>
	<p><% product.description %></p>
	<p><% number_to_currency(product.price, :unit => '$') %></p>
	<p>Quantity: <% quantity %></p>
	</li>
	<% total += quantity * product.price %>
	
<% end %>

<p><b><% number_to_currency(total, :unit => '$') %></b></p>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" type="image/png" sizes="96x96" href="http://i.imgur.com/JDoctbS.png">

	
	<title>	BurgerCore©  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

	<nav id="nav">
		<div id="page_nav">	
			<%= link_to "Home", root_path %>
			<%= link_to "Menu", products_path %>
			<%= link_to "Contact", page_contact_path %>
		</div>

		<div id="sign_in">
			<% if user_signed_in? %>
				<%=link_to "Logout", destroy_user_session_path, method: :delete %>
			<% else %>
				<%=link_to "Login", new_user_session_path %>
				<%=link_to "Sign Up", new_user_registration_path %>
			<% end %>
		</div>
	</nav>

	<div id="main_wrap">
	    <p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>
	    <%= yield %>
	</div>

	

</body>
</html>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- HTML Codes by Quackit.com -->
<title>
BurgerCore©</title>
<meta name="description" content="Your Online Food Delivery Service.">
<style type="text/css">
body {background-color:FFFFFF;background-repeat:no-repeat;background-position:top left;background-attachment:fixed;}
h1{text-align:center;font-family:Cursive;color:000000;}
h2{text-align:center;font-family:Cursive;color:000000;}
p {text-align:justified;font-family:Cursive;font-size:14px;font-style:italic;font-weight:normal;color:000000;}
</style>
</head>
<body>

<img src="http://i.imgur.com/bB18Wk6.png" alt="burgercorelogo" height="250" width="250">

<h1>The BurgerCore©</h1>
<h2>Your Online Burger Service</h2>
<br></br>
<p>Founded in 2015, BurgerCore© is the second smallest World burgers Network. Original home to IDEAFIELD , possesses only one store, Serving Over 2 Consumers IN ON Day 1 Countries Around the World. Since we first opened our doors in 2015, people Have Been coming to The BurgerCore© for a job - and discovering so much more. BurgerCore© offers a chance to learn, grow and gain hands-on experiences can set them up for success - Whether here at The BurgerCore© or anywhere else They Pursue Their opportunities. And the pride that comes from bringing a little lovin 'to our customers every day.</p>

</body>
</html>

app/views/page/menu.html.erb
<h1>Page#menu</h1>
<p>Find me in app/views/page/menu.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
  <h4 class="column">Featured Burgers</h4>
  <div class="column">
    <ul class="burgers-grid no-bullet row">
    <% @products.each do |product| %>
      <li class="large-3 medium-4 small-12 column">
      <div class="product-card padly">
        <%= link_to product, class: "poster" do %>
        <%= image_tag product.image_url %>
        <% end %>
        <div class="product-info ell glassy-bg padmy padlx">
          <div class="name">
            <h6><%= product.title %></h6>
          </div>
        <p class="left price label movie-label radius">$ <%= product.price %></p>
        <td><a href="/cart/<%= product.id %>"> Add To Cart</a></td>
        <% end %>
        </div>
      </div>
      </li>
    </ul>
  </div>
</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>